# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

User.create([
	{username: 'admin', password: 'admin', is_admin: 1},
	{username: 'pedro', password: '1234', is_admin: 0},
	{username: 'gabriel', password: '5678', is_admin: 0},
	{username: 'eduardo', password: 'rapidera', is_admin: 0},
	{username: 'ronaldo', password: 'bmnc', is_admin: 0},
	{username: 'vinicius', password: 'senha', is_admin: 0},
	{username: 'moura', password: 'lei', is_admin: 0},
	{username: 'leila', password: 'flordelis', is_admin: 0},
	{username: 'julia', password: 'jaca', is_admin: 0},
	{username: 'juliana', password: 'jacare', is_admin: 0},
	{username: 'vitoria', password: 'derrota', is_admin: 0},
	{username: 'viviane', password: 'morteane', is_admin: 0},
	{username: 'matheus', password: 'guerra3', is_admin: 0},
	{username: 'otavio', password: 'otario', is_admin: 0},
	{username: 'ivete', password: 'canivete', is_admin: 0},
	{username: 'laura', password: 'croft', is_admin: 0},
	{username: 'lurdes', password: 'luzes', is_admin: 0},
	{username: 'romario', password: 'romaria', is_admin: 0},
	{username: 'mario', password: 'armario', is_admin: 0},
	{username: 'matilda', password: 'ilda', is_admin: 0},
	{username: 'ferreira', password: 'rapidera', is_admin: 0}
])

Genre.create([
	{name: 'Rock'},
	{name: 'MPB'},
	{name: 'Pagode'},
	{name: 'Sertanejo'},
	{name: 'Eletronica'},
	{name: 'Samba'},
	{name: 'Trap'},
	{name: 'PopCity'},
	{name: 'Heavy Metal'},
	{name: 'Bossa Nova'},
	{name: 'Classico'},
	{name: 'Pop'},
	{name: 'Funk'}
])

Artist.create([
	{name: 'Teto'},
	{name: 'Ozzy Osborne'},
	{name: 'Chico Buarque'},
	{name: 'Adriana Calcanhoto'},
	{name: 'Zeca Pagodinho'},
	{name: 'Beethoven'},
	{name: 'Pericles'},
	{name: 'DaftPunk'},
	{name: 'Skrillex'},
	{name: 'Mariya Takeuchi'},
	{name: 'Iron Maiden'},
	{name: 'Tom Jobim'},
	{name: 'Mc Carol'},
	{name: 'Anitta'}
])

Music.create([
	{name: 'Mustangue Preto', likes: '100', artist_id: 1, genre_id: 7, mainartist:'Teto'},
	{name: 'Changes', likes: '10', artist_id: 2, genre_id: 1, mainartist:'Ozzy Osborne'},
	{name: 'Children of the grave', likes: '15', artist_id: 2, genre_id: 1, mainartist:'Ozzy Osborne'},
	{name: 'Crazy Train', likes: '20', artist_id: 2, genre_id: 1, mainartist:'Ozzy Osborne'},
	{name: 'Bark at the moon', likes: '30', artist_id: 2, genre_id: 1, mainartist:'Ozzy Osborne'},
	{name: 'No more tears', likes: '40', artist_id: 2, genre_id: 1, mainartist:'Ozzy Osborne'},
	{name: 'Roda Viva', likes: '20', artist_id: 3, genre_id: 2, mainartist:'Chico Buarque'},
	{name: 'Joao e Maria', likes: '30', artist_id: 3, genre_id: 2, mainartist:'Chico Buarque'},
	{name: 'Construcao', likes: '5', artist_id: 3, genre_id: 2, mainartist:'Chico Buarque'},
	{name: 'Cotudiano', likes: '50', artist_id: 3, genre_id: 2, mainartist:'Chico Buarque'},
	{name: 'Apesar de voce', likes: '50', artist_id: 3, genre_id: 2, mainartist:'Chico Buarque'},
	{name: 'Devolva-me', likes: '27', artist_id: 4, genre_id: 2, mainartist:'Adriana Calcanhoto'},
	{name: 'Vambora', likes: '37', artist_id: 4, genre_id: 2, mainartist:'Adriana Calcanhoto'},
	{name: 'Metade', likes: '57', artist_id: 4, genre_id: 2, mainartist:'Adriana Calcanhoto'},
	{name: 'Mentiras', likes: '57', artist_id: 4, genre_id: 2, mainartist:'Adriana Calcanhoto'},
	{name: 'Esquadros', likes: '57', artist_id: 4, genre_id: 2, mainartist:'Adriana Calcanhoto'},
	{name: 'Deixa a vida me levar', likes: '90', artist_id: 5, genre_id: 3, mainartist:'Zeca Pagodinho'},
	{name: 'Camarao que dorme a onda leva', likes: '110', artist_id: 5, genre_id: 3, mainartist:'Zeca Pagodinho'},
	{name: 'Verdade', likes: '110', artist_id: 5, genre_id: 3, mainartist:'Zeca Pagodinho'},
	{name: 'Ogum', likes: '110', artist_id: 5, genre_id: 3, mainartist:'Zeca Pagodinho'},
	{name: 'Agua da minha sede', likes: '110', artist_id: 5, genre_id: 3, mainartist:'Zeca Pagodinho'},
	{name: 'Fur elise', likes: '3', artist_id: 6, genre_id: 11, mainartist:'Beethoven'},
	{name: 'Sonata ao luar', likes: '3', artist_id: 6, genre_id: 11, mainartist:'Beethoven'},
	{name: 'Sinfonia numero 5', likes: '3', artist_id: 6, genre_id: 11, mainartist:'Beethoven'},
	{name: 'Concerto de violino', likes: '3', artist_id: 6, genre_id: 11, mainartist:'Beethoven'},
	{name: 'Ode a alegria', likes: '3', artist_id: 6, genre_id: 11, mainartist:'Beethoven'},
	{name: 'Ate que durou', likes: '515', artist_id: 7, genre_id: 6, mainartist:'Pericles'},
	{name: 'Melhor eu ir', likes: '510', artist_id: 7, genre_id: 6, mainartist:'Pericles'},
	{name: 'Se eu largar o freio', likes: '522', artist_id: 7, genre_id: 6, mainartist:'Pericles'},
	{name: 'Preciso desabafar', likes: '520', artist_id: 7, genre_id: 6, mainartist:'Pericles'},
	{name: 'Cuidado cupido', likes: '527', artist_id: 7, genre_id: 6, mainartist:'Pericles'},
	{name: 'One More time', likes: '620', artist_id: 8, genre_id: 5, mainartist:'DaftPunk'},
	{name: 'Get Lucky', likes: '727', artist_id: 8, genre_id: 5, mainartist:'DaftPunk'},
	{name: 'Around the World', likes: '72', artist_id: 8, genre_id: 5, mainartist:'DaftPunk'},
	{name: 'Instant Crush', likes: '720', artist_id: 8, genre_id: 5, mainartist:'DaftPunk'},
	{name: 'Harder, Better, Faster, Stronger', likes: '720', artist_id: 8, genre_id: 5, mainartist:'DaftPunk'},
	{name: 'Bangarang', likes: '500', artist_id: 9, genre_id: 7, mainartist:'Skrillex'},
	{name: 'Purple Lamborgini', likes: '490', artist_id: 9, genre_id: 7, mainartist:'Skrillex'},
	{name: 'Ego Death', likes: '480', artist_id: 9, genre_id: 5, mainartist:'Skrillex'},
	{name: 'Plastic Love', likes: '89', artist_id: 10, genre_id: 8, mainartist:'Mariya Takeuchi'},
	{name: 'Eki', likes: '86', artist_id: 10, genre_id: 8, mainartist:'Mariya Takeuchi'},
	{name: 'Single Again', likes: '86', artist_id: 10, genre_id: 8, mainartist:'Mariya Takeuchi'},
	{name: 'Camouflage', likes: '86', artist_id: 10, genre_id: 8, mainartist:'Mariya Takeuchi'},
	{name: 'oh no,oh yes!', likes: '86', artist_id: 10, genre_id: 8, mainartist:'Mariya Takeuchi'},
	{name: 'Brave New World', likes: '150', artist_id: 11, genre_id: 1, mainartist:'Iron Maiden'},
	{name: 'Be quick or be dead', likes: '170', artist_id: 11, genre_id: 1, mainartist:'Teto'},
	{name: 'Two minutes to midnight', likes: '170', artist_id: 11, genre_id: 1, mainartist:'Iron Maiden'},
	{name: 'Ghost of navigator', likes: '170', artist_id: 11, genre_id: 1, mainartist:'Iron Maiden'},
	{name: 'The Chosen one', likes: '170', artist_id: 11, genre_id: 1, mainartist:'Tom Jobim'},
	{name: 'Aguas de março', likes: '240', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Corcovado', likes: '756', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Garota de ipanema', likes: '310', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Wave', likes: '310', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Triste', likes: '310', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Para Machucar o meu coração', likes: '310', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Pela luz dos olhos teus', likes: '310', artist_id: 12, genre_id: 10, mainartist:'Tom Jobim'},
	{name: 'Vampiro', likes: '70', artist_id: 1, genre_id: 7, mainartist:'Teto'},
	{name: 'Fim de semana no rio', likes: '70', artist_id: 1, genre_id: 7, mainartist:'Teto'},
	{name: 'Paypal', likes: '800', artist_id: 1, genre_id: 7, mainartist:'Teto'},
	{name: 'Groupies', likes: '643', artist_id: 1, genre_id: 7, mainartist:'Teto'},
	{name: 'Show das poderosas', likes: '534', artist_id: 14, genre_id: 12, mainartist:'Anitta'},
	{name: 'Envolver', likes: '325', artist_id: 14, genre_id: 12, mainartist:'Anitta'},
	{name: 'Gata', likes: '762', artist_id: 14, genre_id: 12, mainartist:'Anitta'},
	{name: 'Me gusta', likes: '300', artist_id: 14, genre_id: 12, mainartist:'Anitta'},
	{name: 'Banana', likes: '311', artist_id: 14, genre_id: 12, mainartist:'Anitta'},
	{name: 'Juego', likes: '388', artist_id: 14, genre_id: 12, mainartist:'Anitta'},
	{name: 'Bateu uma onda forte', likes: '300', artist_id: 13, genre_id: 13, mainartist:'Mc Carol'},
	{name: 'Liga pro samu', likes: '312', artist_id: 13, genre_id: 13, mainartist:'Mc Carol'},
	{name: 'Jorginho me empresta a 12', likes: '300', artist_id: 13, genre_id: 13, mainartist:'Mc Carol'},
	{name: 'Levanta a mina', likes: '300', artist_id: 13, genre_id: 13, mainartist:'Mc Carol'},
	{name: 'O amor acabou', likes: '300', artist_id: 13, genre_id: 13, mainartist:'Mc Carol'},
	{name: 'M4', likes: '70', artist_id: 1, genre_id: 7, mainartist:'Teto'}
])

Like.create([
	{user_id: 1, music_id: 1},
	{user_id: 1, music_id: 2},
	{user_id: 1, music_id: 3},
	{user_id: 1, music_id: 15},
	{user_id: 1, music_id: 9},
	{user_id: 2, music_id: 3},
	{user_id: 2, music_id: 70},
	{user_id: 2, music_id: 71},
	{user_id: 2, music_id: 72},
	{user_id: 2, music_id: 73},
	{user_id: 3, music_id: 1},
	{user_id: 3, music_id: 40},
	{user_id: 3, music_id: 45},
	{user_id: 3, music_id: 46},
	{user_id: 3, music_id: 47},
	{user_id: 5, music_id: 13},
	{user_id: 5, music_id: 15},
	{user_id: 5, music_id: 17},
	{user_id: 5, music_id: 18},
	{user_id: 5, music_id: 20},
	{user_id: 4, music_id: 7}

])
